"""create narratives and narrative_events tables

Revision ID: 9a7477602886
Revises: 1185c24720af
Create Date: 2026-08-15 16:18:40.238170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7477602886'
down_revision: Union[str, Sequence[str], None] = '1185c24720af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('validity_status', sa.Enum('CANDIDATE', name='narrativevaliditystatus', native_enum=False, length=50), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('EMERGING', name='narrativelifecyclestatus', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narratives_canonical_key'), 'narratives', ['canonical_key'], unique=True)
    op.create_table('narrative_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_narrative_events_narrative_id'), 'narrative_events', ['narrative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narrative_events_narrative_id'), table_name='narrative_events')
    op.drop_table('narrative_events')
    op.drop_index(op.f('ix_narratives_canonical_key'), table_name='narratives')
    op.drop_table('narratives')
    # ### end Alembic commands ###
