"""create narrative_instrument_impacts table

Revision ID: e7eac13d7d4e
Revises: 9a7477602886
Create Date: 2026-08-15 17:21:58.692133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eac13d7d4e'
down_revision: Union[str, Sequence[str], None] = '9a7477602886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrative_instrument_impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Enum('nq', 'btc', 'gold', name='instrument', native_enum=False, length=50), nullable=False),
    sa.Column('direction', sa.Enum('strongly_bearish', 'bearish', 'mixed', 'neutral', 'bullish', 'strongly_bullish', 'uncertain', name='impactdirection', native_enum=False, length=50), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('horizon', sa.Enum('intraday', 'multi_day', 'unknown', name='impacthorizon', native_enum=False, length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confirmation_state', sa.Enum('unconfirmed', 'confirmed', name='impactconfirmationstate', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_instrument_impacts_narrative_id'), 'narrative_instrument_impacts', ['narrative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_narrative_instrument_impacts_narrative_id'), table_name='narrative_instrument_impacts')
    op.drop_table('narrative_instrument_impacts')
    # ### end Alembic commands ###
